### ISSUE TITLE
Fashion Mnist 

### ISSUE THREAD

**Issue by veshitala** [uiuiuiyp/Machine-learning#6]
Fashion MNist Data set  is pretty much Hello world of Deep Learning .I built a model  having 91.55 percent Accuracy .Can you Improve Its Accuracy.

Improve accuracy and explain the idea you used in this

**Comment by uiuiuiyp** [comment]
You can try a smaller version of [ResNet](https://arxiv.org/abs/1512.03385) architecture or even [VGG](https://arxiv.org/abs/1409.1556)'s. That should help. I've written the code as an example, not to get the highest score, but you could try other ideas to improve it!
